#ifndef NII_TETRIS_CONSTANTS
#define NII_TETRIS_CONSTANTS

#define WINDOW_TITLE  "Tetris by Nii Miyo"

#define WINDOW_WIDTH  640
#define WINDOW_HEIGHT 480

#define GRID_WIDTH  10
#define GRID_HEIGHT 20

#define BLOCK_SIZE 16
#define GRID_GAP   2

#define GRID_WIDTH_PIXELS  ((BLOCK_SIZE + GRID_GAP) * (GRID_WIDTH))
#define GRID_HEIGHT_PIXELS (GRID_HEIGHT * (BLOCK_SIZE + GRID_GAP))

#define GRID_START_X  (WINDOW_WIDTH - GRID_WIDTH_PIXELS) / 2
#define GRID_START_Y  WINDOW_HEIGHT - GRID_HEIGHT_PIXELS - (GRID_GAP * 3)

#define GRID_WALL_WIDTH 2

#define DROP_TIME_MS 800

#endif
